# -*- coding: utf-8 -*-
"""Funcion para eliminar contactos sin emial de una lista de excel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MkdZUEGRpA5hA1j1d5cP2exd8_-c65Wq
"""

from google.colab import drive
drive.mount('/content/drive')

pip install pydrive

import pandas as pd
from google.colab import drive

# Función para cargar un archivo Excel desde Google Drive
def cargar_archivo_excel(ruta_archivo):
    try:
        df = pd.read_excel(ruta_archivo)
        print('El archivo se cargó correctamente.')
        return df
    except FileNotFoundError:
        print('El archivo no se encontró en la ruta especificada.')
        
# Montar Google Drive
drive.mount('/content/drive')

# Llamada a la función para cargar el archivo
ruta_archivo = '/content/drive/MyDrive/archivos_web/clientify_contactos.xlsx'
df = cargar_archivo_excel(ruta_archivo)

# Hacer algo con el dataframe cargado, por ejemplo:
df.head()

from google.colab import drive
import pandas as pd
from google.colab import files

def eliminar_contactos_sin_email():
    # Pedimos al usuario que seleccione el archivo Excel a procesar desde Google Drive
    drive.mount('/content/drive')
    nombre_archivo = '/content/drive/MyDrive/archivos_web/clientify_contactos.xlsx'

    # Cargamos el archivo Excel en un dataframe
    df = pd.read_excel(nombre_archivo)

    # Eliminamos las filas que tengan un valor nulo en la columna de correo electrónico
    df = df.dropna(subset=['correo electrónico'])

    # Guardamos el dataframe resultante en un nuevo archivo Excel
    nuevo_nombre_archivo = nombre_archivo.replace('.xlsx', '_sin_email.xlsx')
    df.to_excel(nuevo_nombre_archivo, index=False)

    # Descargamos el archivo resultante
    files.download(nuevo_nombre_archivo)

def eliminar_contactos_sin_correo(df, ruta_salida):
    df.dropna(subset=['correo_electronico'], inplace=True)
    df.to_excel(ruta_salida, index=False)

def eliminar_contactos_sin_correo(df, ruta_salida):
    df.dropna(subset=['correo electrónico'], inplace=True)
    df.to_excel(ruta_salida, index=False)

# Cargar el archivo Excel
ruta_archivo = '/content/drive/MyDrive/archivos_web/clientify_contactos.xlsx'
df = cargar_archivo_excel(ruta_archivo)

# Eliminar los contactos que no tienen correo electrónico y guardar el resultado
ruta_salida = '/content/drive/MyDrive/archivos_web/clientify_contactos_sin_vacios.xlsx'
eliminar_contactos_sin_correo(df, ruta_salida)
print(f"El archivo modificado se guardó en {ruta_salida}")